[package]
name = "opengl_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
my_gl = { git = "https://github.com/DiSaber/my_gl.git" }
